@extends('backend.layouts.app')
@section('title', 'Realisasi')
@section('page-title', 'Kelola Realisasi')
@section('content')
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-bold text-slate-900">Realisasi Tahunan</h2><p class="mt-1 text-sm text-slate-500">Catat capaian, status pencapaian, dan keterangan tiap indikator.</p></div><a href="{{ route('admin.realisasis.create') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-semibold text-white hover:bg-teal-800"><span class="material-symbols-outlined">add</span> Tambah Realisasi</a></div>
<div class="mb-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" class="grid gap-3 lg:grid-cols-[1fr_180px_220px_auto]"><input type="search" name="q" value="{{ request('q') }}" placeholder="Cari nama indikator..." class="rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><select name="tahun" class="rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><option value="">Semua tahun</option>@foreach($tahuns as $tahun)<option value="{{ $tahun }}" @selected((string)request('tahun') === (string)$tahun)>{{ $tahun }}</option>@endforeach</select><select name="status" class="rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><option value="">Semua status</option><option value="tercapai" @selected(request('status') === 'tercapai')>Tercapai</option><option value="belum_tercapai" @selected(request('status') === 'belum_tercapai')>Belum tercapai</option></select><button class="rounded-xl bg-slate-800 px-5 py-3 font-semibold text-white">Terapkan</button></form></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-4">Indikator</th><th class="px-6 py-4">Tahun</th><th class="px-6 py-4">Nilai</th><th class="px-6 py-4">Status</th><th class="px-6 py-4">Pendukung</th><th class="px-6 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($realisasis as $realisasi)<tr class="align-top hover:bg-slate-50"><td class="max-w-md px-6 py-4"><div class="font-semibold text-slate-900">{{ $realisasi->indikator->nama_indikator }}</div><div class="mt-1 text-sm text-slate-500">{{ $realisasi->indikator->pilar->nama }}</div></td><td class="px-6 py-4 font-bold text-teal-700">{{ $realisasi->tahun }}</td><td class="px-6 py-4 text-slate-800">{{ $realisasi->nilai_realisasi !== null ? number_format($realisasi->nilai_realisasi, 2, ',', '.') : '-' }} {{ $realisasi->indikator->satuan }}</td><td class="px-6 py-4">@if($realisasi->status_pencapaian)<span class="rounded-full px-3 py-1 text-xs font-semibold {{ $realisasi->status_pencapaian === 'tercapai' ? 'bg-green-100 text-green-800' : 'bg-amber-100 text-amber-800' }}">{{ $realisasi->status_pencapaian === 'tercapai' ? 'Tercapai' : 'Belum tercapai' }}</span>@else<span class="text-sm text-slate-400">Belum dinilai</span>@endif</td><td class="px-6 py-4 text-sm text-slate-600">{{ $realisasi->data_pendukungs_count }} file</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.realisasis.edit', $realisasi) }}" class="rounded-lg bg-amber-100 p-2 text-amber-700"><span class="material-symbols-outlined text-xl">edit</span></a><form method="POST" action="{{ route('admin.realisasis.destroy', $realisasi) }}" onsubmit="return confirm('Hapus realisasi dan seluruh data pendukungnya?')">@csrf @method('DELETE')<button class="rounded-lg bg-red-100 p-2 text-red-700"><span class="material-symbols-outlined text-xl">delete</span></button></form></div></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-slate-500">Data realisasi tidak ditemukan.</td></tr>@endforelse
</tbody></table></div>@if($realisasis->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $realisasis->links() }}</div>@endif</div>
@endsection
