@extends('backend.layouts.app')
@section('title', 'Berita')
@section('page-title', 'Kelola Berita')
@section('content')
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-bold text-slate-900">Daftar Berita</h2><p class="mt-1 text-sm text-slate-500">Kelola konten informasi untuk halaman publik.</p></div><a href="{{ route('admin.beritas.create') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-semibold text-white hover:bg-teal-800"><span class="material-symbols-outlined">add</span> Tambah Berita</a></div>
<div class="mb-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" class="flex gap-2"><input type="search" name="q" value="{{ request('q') }}" placeholder="Cari judul atau penulis..." class="min-w-0 flex-1 rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><button class="rounded-xl bg-slate-800 px-5 font-semibold text-white">Cari</button></form></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-4">Berita</th><th class="px-6 py-4">Penulis</th><th class="px-6 py-4">Tanggal</th><th class="px-6 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($beritas as $berita)<tr class="align-top hover:bg-slate-50"><td class="max-w-2xl px-6 py-4"><div class="flex items-start gap-4">@if($berita->foto)<img src="{{ Storage::url($berita->foto) }}" alt="" class="h-16 w-24 rounded-lg object-cover">@else<div class="flex h-16 w-24 items-center justify-center rounded-lg bg-slate-100 text-slate-400"><span class="material-symbols-outlined">image</span></div>@endif<div><div class="font-semibold text-slate-900">{{ $berita->judul }}</div><p class="mt-1 text-sm text-slate-500">{{ Str::limit(strip_tags($berita->isi), 100) }}</p></div></div></td><td class="px-6 py-4 text-sm text-slate-600">{{ $berita->penulis ?: '-' }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $berita->created_at->format('d M Y') }}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.beritas.edit', $berita) }}" class="rounded-lg bg-amber-100 p-2 text-amber-700"><span class="material-symbols-outlined text-xl">edit</span></a><form method="POST" action="{{ route('admin.beritas.destroy', $berita) }}" onsubmit="return confirm('Hapus berita ini?')">@csrf @method('DELETE')<button class="rounded-lg bg-red-100 p-2 text-red-700"><span class="material-symbols-outlined text-xl">delete</span></button></form></div></td></tr>@empty<tr><td colspan="4" class="px-6 py-12 text-center text-slate-500">Berita tidak ditemukan.</td></tr>@endforelse
</tbody></table></div>@if($beritas->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $beritas->links() }}</div>@endif</div>
@endsection
