@extends('backend.layouts.app')
@section('title', 'Target')
@section('page-title', 'Kelola Target')
@section('content')
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="text-xl font-bold text-slate-900">Target Tahunan</h2><p class="mt-1 text-sm text-slate-500">Satu indikator hanya dapat memiliki satu target pada setiap tahun.</p></div><a href="{{ route('admin.targets.create') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-semibold text-white hover:bg-teal-800"><span class="material-symbols-outlined">add</span> Tambah Target</a></div>
<div class="mb-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" class="grid gap-3 md:grid-cols-[1fr_220px_auto]"><input type="search" name="q" value="{{ request('q') }}" placeholder="Cari nama indikator..." class="rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><select name="tahun" class="rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><option value="">Semua tahun</option>@foreach($tahuns as $tahun)<option value="{{ $tahun }}" @selected((string)request('tahun') === (string)$tahun)>{{ $tahun }}</option>@endforeach</select><button class="rounded-xl bg-slate-800 px-5 py-3 font-semibold text-white">Terapkan</button></form></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-4">Indikator</th><th class="px-6 py-4">Pilar</th><th class="px-6 py-4">Tahun</th><th class="px-6 py-4">Nilai Target</th><th class="px-6 py-4">Dibuat Oleh</th><th class="px-6 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($targets as $target)<tr class="hover:bg-slate-50"><td class="max-w-md px-6 py-4 font-semibold text-slate-900">{{ $target->indikator->nama_indikator }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $target->indikator->pilar->nama }}</td><td class="px-6 py-4 font-bold text-teal-700">{{ $target->tahun }}</td><td class="px-6 py-4 text-slate-800">{{ $target->nilai_target !== null ? number_format($target->nilai_target, 2, ',', '.') : '-' }} {{ $target->indikator->satuan }}</td><td class="px-6 py-4 text-sm text-slate-600">{{ $target->user?->name ?: '-' }}</td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.targets.edit', $target) }}" class="rounded-lg bg-amber-100 p-2 text-amber-700"><span class="material-symbols-outlined text-xl">edit</span></a><form method="POST" action="{{ route('admin.targets.destroy', $target) }}" onsubmit="return confirm('Hapus target ini?')">@csrf @method('DELETE')<button class="rounded-lg bg-red-100 p-2 text-red-700"><span class="material-symbols-outlined text-xl">delete</span></button></form></div></td></tr>@empty<tr><td colspan="6" class="px-6 py-12 text-center text-slate-500">Data target tidak ditemukan.</td></tr>@endforelse
</tbody></table></div>@if($targets->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $targets->links() }}</div>@endif</div>
@endsection
