@extends('backend.layouts.app')
@section('title', 'Data Pendukung')
@section('page-title', 'Data Pendukung')
@section('content')
<div class="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
    <div><h2 class="text-xl font-bold text-slate-900">Dokumen Pendukung Realisasi</h2><p class="mt-1 text-sm text-slate-500">Unggah bukti, laporan, tabel, atau dokumentasi untuk setiap realisasi.</p></div>
    <a href="{{ route('admin.data-pendukungs.create') }}" class="inline-flex items-center justify-center gap-2 rounded-xl bg-teal-700 px-5 py-3 font-semibold text-white hover:bg-teal-800"><span class="material-symbols-outlined">upload_file</span> Tambah Dokumen</a>
</div>
<div class="mb-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form method="GET" class="flex gap-2"><input type="search" name="q" value="{{ request('q') }}" placeholder="Cari judul atau indikator..." class="min-w-0 flex-1 rounded-xl border-slate-300 focus:border-teal-600 focus:ring-teal-600"><button class="rounded-xl bg-slate-800 px-5 font-semibold text-white">Cari</button></form></div>
<div class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200"><thead class="bg-slate-50 text-left text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-6 py-4">Dokumen</th><th class="px-6 py-4">Indikator</th><th class="px-6 py-4">Tahun</th><th class="px-6 py-4">File</th><th class="px-6 py-4 text-right">Aksi</th></tr></thead><tbody class="divide-y divide-slate-100">
@forelse($dataPendukungs as $dataPendukung)<tr class="align-top hover:bg-slate-50"><td class="px-6 py-4"><div class="font-semibold text-slate-900">{{ $dataPendukung->judul }}</div><div class="mt-1 text-xs text-slate-500">{{ $dataPendukung->created_at->format('d M Y H:i') }}</div></td><td class="max-w-md px-6 py-4"><div class="text-sm font-medium text-slate-800">{{ $dataPendukung->realisasi->indikator->nama_indikator }}</div><div class="mt-1 text-xs text-slate-500">{{ $dataPendukung->realisasi->indikator->pilar->nama }}</div></td><td class="px-6 py-4 font-bold text-teal-700">{{ $dataPendukung->realisasi->tahun }}</td><td class="px-6 py-4"><a href="{{ Storage::url($dataPendukung->file) }}" target="_blank" class="inline-flex items-center gap-2 text-sm font-semibold text-teal-700 hover:underline"><span class="material-symbols-outlined text-xl">download</span> Buka file</a></td><td class="px-6 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.data-pendukungs.edit', $dataPendukung) }}" class="rounded-lg bg-amber-100 p-2 text-amber-700"><span class="material-symbols-outlined text-xl">edit</span></a><form method="POST" action="{{ route('admin.data-pendukungs.destroy', $dataPendukung) }}" onsubmit="return confirm('Hapus dokumen pendukung ini?')">@csrf @method('DELETE')<button class="rounded-lg bg-red-100 p-2 text-red-700"><span class="material-symbols-outlined text-xl">delete</span></button></form></div></td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-slate-500">Data pendukung tidak ditemukan.</td></tr>@endforelse
</tbody></table></div>@if($dataPendukungs->hasPages())<div class="border-t border-slate-200 px-6 py-4">{{ $dataPendukungs->links() }}</div>@endif</div>
@endsection
